### PR TITLE
Fix japanese bug

### PR DESCRIPTION
**Pull request by PhongTaKiai**
- close: #48

### CODE REVIEW

**Comment by mafreud** [comment]
@PhongTaKiai Could you upload the video? I want to check the bug.

**Comment by PhongTaKiai** [comment]
@mafreud before

https://github.com/ailab-dev/app_buy_sell/assets/117698659/b2313cfc-8121-4372-8642-c0c7f06c97d1

fixed:

https://github.com/ailab-dev/app_buy_sell/assets/117698659/6993d5a5-de53-4269-be5f-72ed913da68b

**Comment by mafreud** [comment]
@PhongTaKiai Why don't you use ```useEffect``` to set initial value to textEditingController?

**Comment by PhongTaKiai** [comment]
@mafreud user profile fetch data from firebase but useEffect run first and did not update after fetching

**Pull request merged**
