### PR TITLE
my profile

### PR DESCRIPTION
**Pull request by PhongTaKiai**
- close: #8 

https://github.com/ailab-dev/app_buy_sell/assets/117698659/b39553f1-3cde-4f95-a264-01885c6df6e6

### CODE REVIEW

**Comment by rick1919** [comment]
@PhongTaKiai @mafreud 
Are you planning to create a separate PR for the profile editing feature?
Is it correct to understand that this PR is only for the My Profile top screen?

**Comment by PhongTaKiai** [comment]
> @PhongTaKiai @mafreud 
> 
> Are you planning to create a separate PR for the profile editing feature?
> 
> Is it correct to understand that this PR is only for the My Profile top screen?

@rick1919 edit profile has plan is today

**Comment by rick1919** [comment]
@PhongTaKiai 
>edit profile has plan is today

Okey, Thanks!

**Comment by rick1919** [comment]
@PhongTaKiai @mafreud 
The UI is LGTM.

**Review by mafreud — APPROVED** [review]
LGTM 🎉

**Pull request merged**
