### PR TITLE
edit my profile

### LINKED ISSUE #9: プロフィール編集画面
### Design
スクリーンショット 2024-01-16 17 57 53

### Design's link
https://www.figma.com/file/FYxK9KgFf68uS9nUjZoO8V/prodhub-%E3%82%A2%E3%83%97%E3%83%AA?type=design&node-id=1002-5400&mode=design&t=tGVpt94aQhAJri09-4

### PR DESCRIPTION
**Pull request by PhongTaKiai**
- close #9 

https://github.com/ailab-dev/app_buy_sell/assets/117698659/acafb42e-e44b-4a32-a218-e1ccd2029aed

### CODE REVIEW

**Comment by rick1919** [comment]
@PhongTaKiai @mafreud 
The UI is LGTM.

**Comment by rick1919** [comment]
@PhongTaKiai 
Is it assumed that there's no validation for attaching links in this SNS section for now?

**Comment by PhongTaKiai** [comment]
> @PhongTaKiai 
> 
> Is it assumed that there's no validation for attaching links in this SNS section for now?

@rick1919 i can't validate if input link text

**Comment by rick1919** [comment]
@PhongTaKiai 
> i can't validate if input link text
I see.
I'll make a new issue!

**Review by mafreud — APPROVED** [review]
LGTM 🎉

**Pull request merged**
