### PR TITLE
home page

### PR DESCRIPTION
**Pull request by PhongTaKiai**
- close: #2 
Simulator Screenshot - iPhone 15 Pro - 2024-01-24 at 21 51 37

### CODE REVIEW

**Comment by mafreud** [comment]
@PhongTaKiai, Could you fix merge conflicts and send a review request?

**Comment by PhongTaKiai** [comment]
@mafreud resloved conflicts, thank

**Comment by mafreud** [comment]
@PhongTaKiai Thank you.
@rick1919 UIの確認をお願いします。他のissueもお願いします〜。

**Comment by rick1919** [comment]
@PhongTaKiai @mafreud 
Sorry, I missed that.
The UI is LGTM!

**Pull request closed without merging**
