### PR TITLE
notification

### PR DESCRIPTION
**Pull request by PhongTaKiai**
- close: #6 

https://github.com/ailab-dev/app_buy_sell/assets/117698659/39ff8768-9f82-4007-8e05-5659d77886b9

This pull request introduces changes to support push notifications and to add a notification feature in the application. The changes include modifications to iOS configuration files, addition of Firebase Messaging package, creation of new classes for handling notifications, and UI changes to display notifications.

iOS Configuration Changes:

* [`ios/Runner/Info.plist`](diffhunk://#diff-13a4d9d8e1fcf0ee1bd48f8728d2b8fbb885f9cca317e047a515d06552458b9fR31-R34): Added `UIBackgroundModes` with `remote-notification` to allow the app to receive remote notifications from Firebase Cloud Messaging.
* [`ios/Runner/Runner.entitlements`](diffhunk://#diff-07728c3971548b909a0b16d492a7f2ec97d7a29b59fbd600f14e8cde7c693d28R5-R6): Added `aps-environment` with value `development` to enable Apple Push Notification service (APNs) in the development environment.

Firebase Messaging Integration:

* [`lib/main.dart`](diffhunk://#diff-e61eb31d013d12616f5532636a88cfa63631dda8f7829e5424e68542214d1608R5): Imported `firebase_messaging` package and requested permission for notifications. [[1]](diffhunk://#diff-e61eb31d013d12616f5532636a88cfa63631dda8f7829e5424e68542214d1608R5) [[2]](diffhunk://#diff-e61eb31d013d12616f5532636a88cfa63631dda8f7829e5424e68542214d1608R14-R16)

New Classes for Notifications:

* [`lib/src/features/home/application/app_service.dart`](diffhunk://#diff-4a020aafc67506bcbe7b8c542b0f0ac765f9611e6009666798d09443c25cb9edR1-R36): Created `AppService` class for handling app-related operations.
* [`lib/src/features/notification/domain/notification_model.dart`](diffhunk://#diff-630da78a670db86f79c2791f02404e22a7ff8083d32d4cb0b8529e402c274b96R1-R41): Created `NotificationModel` class to represent a notification.
* [`lib/src/features/notification/domain/notification_model.freezed.dart`](diffhunk://#diff-5ec1a33b45812cabaa55664b3ceb0e34bb6c3d64e93def5082cb7f7015452aebR1-R345): Auto-generated file for `NotificationModel` class.
* [`lib/src/features/notification/domain/notification_model.g.dart`](diffhunk://#diff-cb49ac84894a8abb67c99c56d4cd65e8916321246d0d5b99c766daab69155c73R1-R43): Auto-generated file for JSON serialization of `NotificationModel`.
* [`lib/src/features/notification/provider/notification_provider.dart`](diffhunk://#diff-3d130ba0e6d94f53ac96a71473b7214efcd2abc86716de286b3a6449f506a2f2R1-R50): Created `NotificationList` class to fetch notifications from Firestore.

UI Changes:

* [`lib/src/features/home/presentation/home_page.dart`](diffhunk://#diff-d7d4d96f1b8b4d807d7cc0f6dc10f5893274f4132e291e89647d0832bad31452L37-R39): Added an action to navigate to the notification page.
* [`lib/src/features/notification/presentation/notification_page.dart`](diffhunk://#diff-0c25edd366cf02207fbdf5fc407d3c8347f8a1eecee4adf005be08fe5a95a4c7R1-R112): Created `NotificationPage` class to display the list of notifications.

### CODE REVIEW

**Comment by mafreud** [comment]
@PhongTaKiai Where is the Cloud Functions' code?

**Comment by mafreud** [comment]
@PhongTaKiai, Could you show us a video of the device receiving FCM?

**Comment by DuyenTran2209** [comment]
@mafreud cc @PhongTaKiai 
お疲れ様です。
アプリの購入後とアプリ掲載の通知がありますので、
こちらはアプリ掲載画面の実装が完了した後で、引き続き実装したいと思います。
何卒よろしくお願い申し上げます。

**Comment by PhongTaKiai** [comment]
> @PhongTaKiai, Could you show us a video of the device receiving FCM?

https://github.com/ailab-dev/app_buy_sell/assets/117698659/3604ca5d-be78-4d87-99c5-99081753f34f
@mafreud I uploaded video

**Comment by PhongTaKiai** [comment]
https://github.com/ailab-dev/app_buy_sell/assets/117698659/2e140c55-f782-4f67-a976-9c18c493ec43

@mafreud I updated android video

**Comment by mafreud** [comment]
@PhongTaKiai Please use a physical device.

**Comment by PhongTaKiai** [comment]
https://github.com/ailab-dev/app_buy_sell/assets/117698659/ab170428-5c1b-4daf-a8f6-0e88fa6551f8
@mafreud updated. Thank

**Pull request merged**
